language: perl
perl:
  - "5.20"
before_install:
	- sudo apt-get install libgmp-dev
    - cpanm Test::Pod # optional dependency
install:
	- cpanm --quiet --installdeps --notest .
#    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .
	


notifications:
  recipients:
    - eduardo@web2solutions.com.br
  email:
    on_success: change
    on_failure: always