language: "perl"
perl:
  - "5.20"
#  - "5.18"

before_install:
    - cpanm Mojolicious # optional dependency

install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

#script: "perl Build.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - eduardo@web2solutions.com.br
  email:
    on_success: change
    on_failure: always
#env: